version: '3.2'

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      RABBITMQ_DEFAULT_USER: kyh0703
      RABBITMQ_DEFAULT_PASS: 12341234