apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: docker.pkg.github.com/csantanapr/docker/knative-samples_helloworld-go
  imagePullSecrets:
  - name: regcred